insert into game_store_test.sales_tax_rate (state,rate) values ("AL",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("AK",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("AZ",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("AR",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("CA",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("CO",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("CT",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("DE",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("FL",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("GA",.07);
insert into game_store_test.sales_tax_rate (state,rate) values ("HI",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("ID",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("IL",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("IN",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("KS",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("KY",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("LA",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("ME",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("MD",.07);
insert into game_store_test.sales_tax_rate (state,rate) values ("MA",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("MI",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("MN",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("MO",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("MT",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("NE",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("NV",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("NH",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("NJ",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("NY",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("NC",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("ND",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("OH",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("OK",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("OR",.07);
insert into game_store_test.sales_tax_rate (state,rate) values ("PA",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("RI",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("SC",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("SD",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("TN",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("TX",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("UT",.04);
insert into game_store_test.sales_tax_rate (state,rate) values ("VT",.07);
insert into game_store_test.sales_tax_rate (state,rate) values ("VA",.06);
insert into game_store_test.sales_tax_rate (state,rate) values ("WA",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("WV",.05);
insert into game_store_test.sales_tax_rate (state,rate) values ("WI",.03);
insert into game_store_test.sales_tax_rate (state,rate) values ("WY",.04);



insert into game_store_test.processing_fee (product_type , fee) values ("Consoles",14.99);
insert into game_store_test.processing_fee (product_type , fee) values ("T-Shirts",1.98);
insert into game_store_test.processing_fee (product_type , fee) values ("Games",1.49);